import "./globals.css";
import Header from "./components/header";
import Footer from "./components/footer";

export const metadata = {
  title: "MMPOC",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div>
          <div>
            <Header />
          </div>
          {children}
          <div>
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
